{% set name = "sphinx-automodapi" %}
{% set version = "0.6" %}
{% set hash_type = "sha256" %}
{% set hash_value = "81449bdb5d048c5ec4e526dc72fd3535442910c5f6efc0c8a657082357e4f254" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch_python: True
  number: 1
  script: python setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - sphinx >1.3
  run:
    - python
    - sphinx >1.3


  home: http://astropy.org
  license: BSD License
  license_family: BSD
  license_file: ''
  summary: Sphinx extension for auto-generating API documentation for entire modules
  description: "|Travis Status| |AppVeyor status| |Coverage Status| |PyPI|\n\nAbout\n=====\n\nThis is a Sphinx extension to automatically generate API pages for whole\nmodules. It was originally developed\
    \ for the Astropy project but is now\navailable as a standalone package since it can be used for any other\npackage. The documentation can be found on\n`ReadTheDocs <http://sphinx-automodapi.readthedocs.io/en/latest/>`_.\n\
    \n*Note that packages from the Astropy project should continue to use this\nextension from the astropy-helpers rather than using this standalone\npackage.*\n\n.. |Travis Status| image:: https://travis-ci.org/astropy/sphinx-automodapi.svg?branch=master\n\
    \   :target: https://travis-ci.org/astropy/sphinx-automodapi\n.. |AppVeyor status| image:: https://ci.appveyor.com/api/projects/status/warwyfj06t1rkn5p/branch/master?svg=true\n   :target: https://ci.appveyor.com/project/Astropy/sphinx-automodapi/branch/master\n\
    .. |Coverage Status| image:: https://coveralls.io/repos/github/astropy/sphinx-automodapi/badge.svg?branch=master\n   :target: https://coveralls.io/github/astropy/sphinx-automodapi?branch=master\n..\
    \ |PyPI| image:: https://img.shields.io/pypi/v/sphinx-automodapi.svg\n   :target: https://pypi.python.org/pypi/sphinx-automodapi\n\n\n"
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
