{% set data = load_setup_py_data() %}


package:
  name: ctapipe
  version: {{ data.get('version') }} # auto-fetch version from package
  

source:
  #path_url:
  # which branch/tag to use (should be a vX.X release)
  git_rev: v0.3.4
  git_url: https://github.com/cta-observatory/ctapipe.git

  
build:
  number: 2 ##{{ GIT_DESCRIBE_NUMBER }}  # adds number of commits past git_rev
  binary_relocation: True
  detect_binary_files_with_prefix: True
  
  entry_points:
    # here must list everything in the entry_points in ctapipe's setup.py
    - ctapipe-info = ctapipe.tools.info:main
    - ctapipe-camdemo = ctapipe.tools.camdemo:main
    - ctapipe-dump-triggers = ctapipe.tools.dump_triggers:main
    - ctapipe-flow = ctapipe.flow.flow:main
    
requirements:
  build:
    # these must match the install_requires list in ctapipe's setup.py
    # they should be reduced to the minimum. They are the packages
    # needed to run python setup.py install
    - python   ## note don't specify version here to make a version-specific package (e.g. with py35 appended and python3.x in the install path
    - setuptools
    - astropy
    - matplotlib
    - scikit-learn
    - scipy
    - traitlets
    - pyhessio ==2.0
  run:
    # these should be all packages that should be installed if ctapipe
    # is installed, so should include all necsesary dependencies
    - python
    - astropy >=1.0
    - matplotlib >=1.3
    - scikit-learn
    - scipy
    - pyhessio ==2.0
    - traitlets
    - pyzmq
    - graphviz

test:
  imports:
     - ctapipe
     - ctapipe.io 
     - ctapipe.core
     - ctapipe.coordinates
     - ctapipe.instrument
     - ctapipe.visualization
     - ctapipe.tools
     - ctapipe.utils
     - ctapipe.reco
  commands:
#    - ctapipe-info --version

about:
  home: https://github.com/cta-observatory/ctapipe
  license: BSD
