package:
  name: pyhessio
  version: 1.0.0

source:
  git_url: https://github.com/cta-observatory/pyhessio
  git_branch: master

build:
  number: 2
  binary_relocation: True
  detect_binary_files_with_prefix: True

requirements:
  build:
    - python
    - numpy
  run:
    - python
    - numpy
