package:
  name: pyhessio
  version: 1.0.1

source:
  url: https://github.com/cta-observatory/pyhessio/archive/v1.0.1.tar.gz
  md5: 54996d5d7f976345f33161097d27567e
  
build:
  number: 2
  binary_relocation: True
  detect_binary_files_with_prefix: True

requirements:
  build:
    - python
    - numpy
  run:
    - python
    - numpy
