package:
  name: gammalib
  version: 1.2.0
  

source:
  url: http://cta.irap.omp.eu/ctools/releases/gammalib/gammalib-1.2.0.tar.gz
  md5: a2751da55f7b97d48db57156e8096792
  
build:
  number: 1 
  binary_relocation: True
  detect_binary_files_with_prefix: True
      
requirements:
  build:
    - python  
    - setuptools
    - cfitsio
    - swig
  run:
    - python
    - cfitsio

about:
  home: http://gammalib.sourceforge.net/
  license: GPL3
