package:
  name: prov
  version: "1.5.0"

source:
  fn: prov-1.5.0.tar.gz
  url: https://pypi.python.org/packages/7f/d6/85f0e363549423f9053c249e8df0001f4b3ea4bda6219a421521c689db00/prov-1.5.0.tar.gz
  md5: 6814538f38f3884ff8b6a8ac51b7fc01
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - prov = prov:main
    #
    # Would create an entry point called prov that calls prov.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - python-dateutil
    - networkx
    - lxml
    - six >=1.9.0
    - rdflib >=4.2.1

  run:
    - python
    - python-dateutil
    - networkx
    - lxml
    - six >=1.9.0
    - rdflib >=4.2.1

test:
  # Python imports
  imports:
    - dev
    - prov
    - prov.serializers
    - prov.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - pydotplus
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/trungdong/prov
  license: MIT License
  summary: 'A library for W3C Provenance Data Model supporting PROV-JSON, PROV-XML and PROV-O (RDF)'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
