{% set data = load_setup_py_data() %}


package:
  name: ctapipe-extra
  version: {{ data.get('version') }} # auto-fetch version from package
  

source:
  #path_url:
  # which branch/tag to use (should be a vX.X release)
  git_rev: master
  git_url: https://github.com/cta-observatory/ctapipe-extra.git

  
build:
  noarch_python: True
  # string has to have just py in it for noarch build to work
  string: py_{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}

requirements:
  build:
    # these must match the install_requires list in ctapipe's setup.py
    # they should be reduced to the minimum. They are the packages
    # needed to run python setup.py install
    - setuptools

about:
  home: https://github.com/cta-observatory/ctapipe-extra
  license: BSD
