{% set data = load_setup_py_data() %}

package:
  name: ctapipe-extra
  version: {{ data.get('version') }}
  

source:
  #path: /Users/kosack/Projects/CTA/Working/ctapipe-extra
  url: https://github.com/cta-observatory/ctapipe-extra/archive/v0.2.2.tar.gz
  # which branch/tag to use (should be a vX.X release)
  #git_rev: master
  #git_url: https://github.com/cta-observatory/ctapipe-extra.git

  
build:
  noarch: python
  # string has to have just py in it for noarch build to work
  string: py_0

requirements:
  build:
    - setuptools

about:
  home: https://github.com/cta-observatory/ctapipe-extra
  license: BSD
