package:
  name: ctools
  version: 1.2.0
  

source:
  url: http://cta.irap.omp.eu/ctools/releases/ctools/ctools-1.2.0.tar.gz
  md5: 949de4da921e0f516b805c417d6ce914
  
build:
  number: 2
  binary_relocation: True
  detect_binary_files_with_prefix: True
      
requirements:
  build:
    - python  
    - setuptools
    - cfitsio
    - swig
    - gammalib ==1.2
  run:
    - python
    - cfitsio
    - gammalib ==1.2

about:
  home: cta.irap.omp.eu/ctools/releases/ctools/ctools-1.2.0.tar.gz
  license: GPL3
