package:
  name: dl1_data_handler
  version: "0.8.0"

source:
  git_url: https://github.com/cta-observatory/dl1-data-handler.git
  git_rev: v0.8.0

build:
  number: 0

requirements:
  build:
    - ctapipe >=0.6.2
    - eventio>=0.11.0
    - ctapipe-extra >=0.2.17
    - pytables >=3.4.4
    - pyhessio >=2.1.1
    - astropy
    - scipy  
  host:
    - ctapipe >=0.6.2
    - eventio>=0.11.0
    - ctapipe-extra >=0.2.17
    - pytables >=3.4.4
    - pyhessio >=2.1.1
    - astropy
    - scipy
  run:
    - ctapipe >=0.6.2
    - eventi>o=0.11.0
    - ctapipe-extra >=0.2.17
    - pytables >=3.4.4
    - pyhessio >=2.1.1
    - astropy
    - scipy
  test:
    imports:
      - dl1-data-handler

about:
  home: https://github.com/cta-observatory/dl1-data-handler
  license: MIT
  license_file: LICENSE
  summary: DL1 to PyTables HDF5 data dumper/writer/processor for ML studies.
extra:
  recipe-maintainers:
    - bryankim96
    - aribrill
    - nietootein
